apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
      - name: predict-container
        image: mertmenevse/predict:latest   # <-- Replace with your Docker Hub kullan覺c覺 ad覺n覺z
        ports:
        - containerPort: 5000