# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      labels:
        app: predict
    spec:
      containers:
      - name: predict-container
        image: mertmenevse/predict:latest  # Docker Hub'daki imaj adı
        ports:
        - containerPort: 5000  # Flask varsayılan portu